export const NEWS_RECEIVED = 'NEWS_RECEIVED'
export const NEWSITEM_RECEIVED = 'NEWSITEM_RECEIVED'
export const NEWSITEM_LOADING = 'NEWSITEM_LOADING'
export const NEWS_SUBMIT = 'NEWS_SUBMIT'

export const USER_REGISTERED = 'USER_REGISTERED'
export const USER_LOGGEDIN = 'USER_LOGGEDIN'
export const USER_LOGOUT = 'USER_LOGOUT'

export const NEWS_ADDCOMMENT = '  NEWS_ADDCOMMENT'